export default {
    UPDATE_AVATAR: 'UPDATE_AVATAR',
    UPDATE_BANNER: 'UPDATE_BANNER',
    UPLOAD_USER: 'UPLOAD_USER',
    SET_AVATAR: 'SET_AVATAR',
    SET_BANNER: 'SET_BANNER',
    SET_USER: 'SET_USER',
    SET_IS_AUTH: 'SET_IS_AUTH',
    TOGGLE_IS_LOADING: 'TOGGLE_IS_LOADING'
}
