export default {
    UPDATE_AVATAR: 'UPDATE_AVATAR',
    UPDATE_BANNER: 'UPDATE_BANNER',
    UPLOAD_USER: 'UPLOAD_USER',
    SET_AVATAR: 'SET_AVATAR',
    SET_BANNER: 'SET_BANNER',
    SET_USER: 'SET_USER',
    SET_IS_AUTH: 'SET_IS_AUTH',
    SET_IS_FOLLOWER: 'SET_IS_FOLLOWER',
    INCREMENET_FOLLOWERS: 'INCREMENET_FOLLOWERS',
    DECREMENET_FOLLOWERS: 'DECREMENET_FOLLOWERS',
    TOGGLE_IS_LOADING: 'TOGGLE_IS_LOADING',
    FOLLOW: 'FOLLOW',
    UNFOLLOW: 'UNFOLLOW',
    SET_TOTAL_VIEWS: 'SET_TOTAL_VIEWS',

}
