export default {
    SEARCH_INIT_DATA: 'SEARCH_INIT_DATA',
    ACTIVATE_IS_LOADING: 'ACTIVATE_IS_LOADING',
    DEACTIVATE_IS_LOADING: 'DEACTIVATE_IS_LOADING',
    SET_USERS: 'SET_USERS',
    INIT: 'INIT',
}
