export default {
    TOGGLE_IS_LOADING: 'TOGGLE_IS_LOADING',
    GET_VIDEOS: 'GET_VIDEOS',
    SET_VIDEOS: 'SET_VIDEOS',
    INCREMENET_VIEWS: 'INCREMENET_VIEWS',
    UPLOAD_COMMENTS: 'UPLOAD_COMMENTS',
    SET_COMMENTS: 'SET_COMMENTS',
    TOGGLE_SOUND: 'TOGGLE_SOUND',
    UPDATE_VIDEO_SPEED: 'UPDATE_VIDEO_SPEED',
    TOGGLE_IS_FULLSCREEN: 'TOGGLE_IS_FULLSCREEN',
    TOGGLE_IS_COMMENTS_OPENED: 'TOGGLE_IS_COMMENTS_OPENED',
    SET_LAST_PAGE: 'SET_LAST_PAGE',
    GET_NEW_VIDEOS: 'GET_NEW_VIDEOS',
    SET_HOME_VIDEOS: 'SET_HOME_VIDEOS',
    TOGGLE_SHOW_VIDEOS: 'TOGGLE_SHOW_VIDEOS',
    GET_TRENDING_VIDEOS: 'GET_TRENDING_VIDEOS'
}
